version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: LearnASP/Dockerfile.dev
    ports:
      - "5113:5113"
    volumes:
      - ./LearnASP/.:/app
  
  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=learnasp
    ports:
      - 5432:5432

volumes:
  postgres_data: